M48
; DRILL file {KiCad 8.0.8-8.0.8-0~ubuntu24.04.1} date 2025-08-05T21:13:54-0400
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2025-08-05T21:13:54-04:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,8.0.8-8.0.8-0~ubuntu24.04.1
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0256
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.0370
%
G90
G05
T1
X7.9543Y-4.0435
X8.1819Y-4.0435
T2
X8.7402Y-3.2614
X8.7402Y-3.3795
M30
